Fixes many dependency errors
fix broken ccxt dependancy
1.21.22 doesn't exist (https://pypi.org/project/ccxt/1.23.1/#history)

fin numpy

fix broken tensorboard dependancy

ERROR: Cannot install -r binder/requirements.txt (line 53) and tensorboard==2.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tensorboard==2.2.2
    tensorflow 2.5.1 depends on tensorboard~=2.5

fix broken tensorflow-estimator